language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - pecl install -f ast

install:
  - rm -f composer.lock  # workaround for testing among different PHP versions
  - composer install --prefer-dist --no-progress

script:
  - composer run-script analyze
  - composer run-script test
